#pragma once

using namespace ATL;

template <class T>
class CProxy_IWebRTCAPIEvents : public IConnectionPointImpl<T, &__uuidof(_IWebRTCAPIEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
